### ISSUE TITLE
Please help me !!!

### ISSUE THREAD

**Issue by tady0725** [SleepTheGod/iPhone-SSH-Backdoor#2]
I use a mac system to connect with usb, and try to execute the backdoor shell, but I can't succeed, can you give me detailed steps to execute, thank you

**Comment by SleepTheGod** [comment]
check main.sh

**Comment by SleepTheGod** [comment]
> I use a mac system to connect with usb, and try to execute the backdoor shell, but I can't succeed, can you give me detailed steps to execute, thank you

Ensure you have a way to retrieve the actual unique identifier for the device. The placeholder unique-identifier-placeholder needs to be replaced with logic to obtain the actual identifier from connected devices.

git clone https://github.com/SleepTheGod/iPhone-SSH-Backdoor/
cd iPhone-SSH-Backdoor
chmod +x kali.sh
bash kali.sh
