### ISSUE TITLE
2

### ISSUE THREAD

**Issue by 1764549853** [SleepTheGod/iPhone-SSH-Backdoor#4]
kali what system do I need to run it, when I tried kali linux in a virtual machine it failed without a doubt, I can't use it in windows as well, I put x permissions on it but it doesn't work!

**Comment by SleepTheGod** [comment]
sudo apt update
sudo apt install git autoconf automake libtool libplist-dev libusbmuxd-dev
launchctl stop com.openssh.sshd
launchctl start com.openssh.sshd
sudo systemctl restart ssh

Ensure you have a way to retrieve the actual unique identifier for the device. The placeholder unique-identifier-placeholder needs to be replaced with logic to obtain the actual identifier from connected devices.

then run kali.sh from the updated repo
